# Generated by Django 3.1.2 on 2021-08-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_post_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
